workaround to develop_install on mac

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -56,14 +56,29 @@ jobs:
           eval "$(conda shell.bash hook)"
           conda config --set channel_priority strict
       - name: doit develop_install
+        if: matrix.os != 'macos-latest'
         run: |
           eval "$(conda shell.bash hook)"
           conda activate test-environment
           conda list
           doit develop_install ${{ env.CHANS_DEV}} -o examples -o recommended
+
+      # Temporary step for Mac only due to develop_install failing (reason not yet found)
+      - name: doit develop_install
+        if: matrix.os == 'macos-latest'
+        run: |
+          eval "$(conda shell.bash hook)"
+          conda activate test-environment
+          conda list
+          doit develop_install ${{ env.CHANS_DEV}} -o examples -o recommended || echo "Keep going"
+          pip install --no-deps --no-build-isolation -e .
+
+      - name: download test data
+        run: |
           bokeh sampledata
           geoviews fetch-data --path=examples
-          echo "-----"
+      - name: git describe
+        run: |
           git describe
       - name: Pin matplotlib on python 3.8 because of issues with fiona
         if: matrix.os == 'macos-latest' && matrix.python-version == '3.8'
